In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv('/content/video_features_TD12.csv')

In [ ]:
data

,FaceRectX,FaceRectY,FaceRectWidth,FaceRectHeight,FaceScore,x_0,x_1,x_2,x_3,x_4,...,AU43,anger,disgust,fear,happiness,sadness,surprise,neutral,input,frame
0,707.609049,165.982853,114.994683,142.912800,0.998912,703.980596,705.144474,707.889384,712.233391,719.461137,...,0.035835,0.120289,0.000075,0.000357,0.005203,0.085017,0.003296,0.785764,/content/data/frame0.jpg,0
1,707.609049,165.982853,114.994683,142.912800,0.998912,703.980596,705.144474,707.889384,712.233391,719.461137,...,0.035835,0.120289,0.000075,0.000357,0.005203,0.085017,0.003296,0.785764,/content/data/frame1.jpg,0
2,708.577908,168.710020,113.120117,140.438524,0.998621,704.083655,705.234356,707.920890,712.075311,718.923579,...,0.039718,0.333949,0.000068,0.000242,0.003969,0.126152,0.000578,0.535042,/content/data/frame2.jpg,0
3,708.305990,168.137598,113.925130,141.778685,0.998800,703.852398,705.000030,707.750613,711.933613,718.880166,...,0.034375,0.149239,0.000078,0.000239,0.003047,0.083894,0.001536,0.761968,/content/data/frame3.jpg,0
4,708.506565,167.563271,114.471571,142.356892,0.999080,704.196937,705.254917,707.851102,711.826632,718.559498,...,0.044677,0.214863,0.000076,0.000293,0.002620,0.086152,0.002026,0.693970,/content/data/frame4.jpg,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3256,706.547472,175.417809,113.971842,147.987453,0.998080,699.518587,701.159584,704.311326,708.567917,715.492429,...,0.038579,0.332369,0.000050,0.000196,0.001298,0.026581,0.001627,0.637879,/content/data/frame3256.jpg,0
3257,706.417209,175.181534,114.223416,148.250336,0.998072,699.531304,701.169213,704.327599,708.608550,715.566466,...,0.032335,0.344210,0.000049,0.000199,0.001230,0.027419,0.001532,0.625360,/content/data/frame3257.jpg,0
3258,706.417209,175.181534,114.223416,148.250336,0.998072,699.531304,701.169213,704.327599,708.608550,715.566466,...,0.032335,0.344210,0.000049,0.000199,0.001230,0.027419,0.001532,0.625360,/content/data/frame3258.jpg,0
3259,706.708388,173.739424,114.617459,150.295149,0.997001,699.676586,701.403598,704.595031,709.147741,716.563449,...,0.024469,0.266987,0.000053,0.000156,0.001899,0.035513,0.000778,0.694614,/content/data/frame3259.jpg,0
3260,707.314399,174.870432,113.877604,147.873968,0.998217,700.652149,702.176071,705.302652,709.800249,717.090245,...,0.063650,0.197667,0.000055,0.000174,0.001309,0.039447,0.002311,0.759038,/content/data/frame3260.jpg,0

In [ ]:
l1 = []

In [ ]:
for i in range(0,len(data)):
  if data['AU06'][i]> 0.191667 and data['AU12'][i]>0.141667:
    l1.append("yes")
  else:
    l1.append("no")
data['Are there signs of Unusual/ excessive smiling?'] = l1
l1 = []
for i in range(0,len(data)):
  if data['AU43'][i]> 0.216667 and data['AU06'][i]> 0.191667 and data['AU09'][i]> 0.15:
    l1.append("yes")
  else:
    l1.append("no")
data['Is the face asymmetric(FA)?'] = l1
l1 = []
for i in range(0,len(data)):
  if(data['AU25'][i]> 0.333333 and data['AU26'][i]> 0.15):
    l1.append("yes")
  else:
    l1.append("no")
data['Are their lips parted?'] = l1
l1 = []
for i in range(0,len(data)):
  if data['AU06'][i]>0.191667:
    l1.append("yes")
  else:
    l1.append("no")
data['Are cheeks puffed or raised with happiness?'] = l1
l1 = []
for i in range(0,len(data)):
  if data['AU20'][i]> 0.083333:
    l1.append("yes")
  else:
    l1.append("no")
data['Are there any noticeable lip movements, (such as lip pursing, biting, or smacking, exhibited by the child in the video) ?'] = l1
l1 = []
for i in range(0,len(data)):
  if data['AU15'][i]> 0.4:
    l1.append("yes")
  else:
    l1.append("no")
data['Does the lip corner depressor show discomfort or stress?'] = l1
l1 = []
for i in range(0,len(data)):
  if(data['AU25'][i]> 0.333333 and data['AU26'][i]> 0.15):
    l1.append("yes")
  else:
    l1.append("no")
data['Are there signs of jaw clenching or teeth grinding?'] = l1
l1 = []
for i in range(0,len(data)):
  if(data['AU43'][i]> 0.216667):
    l1.append("yes")
  else:
    l1.append("no")
data[' Does the child have reduced eye contact?'] = l1
l1 = []
for i in range(0,len(data)):
  if(data['AU43'][i]> 0.216667):
    l1.append("yes")
  else:
    l1.append("no")
data['Does the child have atypical gaze patterns?'] = l1
l1 = []
for i in range(0,len(data)):
  if(data['AU04'][i]> 0.216667):
    l1.append("yes")
  else:
    l1.append("no")
data['Are the inner portions of the brows furrowed horizontally?'] = l1
l1 = []
for i in range(0,len(data)):
  if(data['AU01'][i]>0.491667):
    l1.append("yes")
  else:
    l1.append("no")
data['Is there absence of the inner brow raiser?'] = l1

In [ ]:
data

,FaceRectX,FaceRectY,FaceRectWidth,FaceRectHeight,FaceScore,x_0,x_1,x_2,x_3,x_4,...,Is the face asymmetric(FA)?,Are their lips parted?,Are cheeks puffed or raised with happiness?,"Are there any noticeable lip movements, (such as lip pursing, biting, or smacking, exhibited by the child in the video) ?",Does the lip corner depressor show discomfort or stress?,Are there signs of jaw clenching or teeth grinding?,Does the child have reduced eye contact?,Does the child have atypical gaze patterns?,Are the inner portions of the brows furrowed horizontally?,Is there absence of the inner brow raiser?
0,707.609049,165.982853,114.994683,142.912800,0.998912,703.980596,705.144474,707.889384,712.233391,719.461137,...,no,no,no,no,yes,no,no,no,yes,yes
1,707.609049,165.982853,114.994683,142.912800,0.998912,703.980596,705.144474,707.889384,712.233391,719.461137,...,no,no,no,no,yes,no,no,no,yes,yes
2,708.577908,168.710020,113.120117,140.438524,0.998621,704.083655,705.234356,707.920890,712.075311,718.923579,...,no,no,no,no,yes,no,no,no,yes,no
3,708.305990,168.137598,113.925130,141.778685,0.998800,703.852398,705.000030,707.750613,711.933613,718.880166,...,no,no,no,no,yes,no,no,no,yes,no
4,708.506565,167.563271,114.471571,142.356892,0.999080,704.196937,705.254917,707.851102,711.826632,718.559498,...,no,no,no,no,no,no,no,no,yes,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3256,706.547472,175.417809,113.971842,147.987453,0.998080,699.518587,701.159584,704.311326,708.567917,715.492429,...,no,no,yes,no,no,no,no,no,yes,no
3257,706.417209,175.181534,114.223416,148.250336,0.998072,699.531304,701.169213,704.327599,708.608550,715.566466,...,no,no,yes,no,no,no,no,no,yes,no
3258,706.417209,175.181534,114.223416,148.250336,0.998072,699.531304,701.169213,704.327599,708.608550,715.566466,...,no,no,yes,no,no,no,no,no,yes,no
3259,706.708388,173.739424,114.617459,150.295149,0.997001,699.676586,701.403598,704.595031,709.147741,716.563449,...,no,no,yes,no,yes,no,no,no,yes,no
3260,707.314399,174.870432,113.877604,147.873968,0.998217,700.652149,702.176071,705.302652,709.800249,717.090245,...,no,no,yes,no,yes,no,no,no,yes,no

In [ ]:
data.to_csv('feature12.csv')