In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv('/content/bmc2.csv')

In [ ]:
data

,FaceRectX,FaceRectY,FaceRectWidth,FaceRectHeight,FaceScore,x_0,x_1,x_2,x_3,x_4,...,AU43,anger,disgust,fear,happiness,sadness,surprise,neutral,input,frame
0,865.570692,336.203133,317.611057,407.807968,0.998354,859.437006,864.554202,873.272245,885.788089,905.461516,...,0.134147,0.351344,0.002122,0.002437,0.005787,0.360904,0.000463,0.276944,/content/data/frame0.jpg,0
1,865.890245,333.035362,319.283474,412.016899,0.998237,856.599958,862.850322,872.695581,885.721312,905.220978,...,0.152491,0.344311,0.002641,0.001909,0.002899,0.449838,0.000355,0.198046,/content/data/frame1.jpg,0
2,865.740994,334.909630,317.141819,408.372253,0.997989,855.189773,861.477001,871.240480,884.175150,903.595056,...,0.150725,0.401311,0.003276,0.002688,0.004147,0.352803,0.000700,0.235074,/content/data/frame2.jpg,0
3,863.868815,334.156792,313.655382,410.975189,0.998086,855.206640,861.090611,870.471204,883.376778,902.641975,...,0.662418,0.363627,0.002170,0.002040,0.003688,0.440726,0.000604,0.187144,/content/data/frame3.jpg,0
4,864.068142,331.252728,308.735243,410.773899,0.998166,851.017937,858.243559,868.302964,881.814315,901.802886,...,0.453664,0.438016,0.005391,0.002541,0.003323,0.324187,0.000677,0.225865,/content/data/frame4.jpg,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1385,955.890734,329.181942,317.982964,408.483799,0.996393,948.038917,951.542771,958.343730,968.663875,985.946973,...,0.166332,0.245433,0.001485,0.003738,0.019719,0.093912,0.002685,0.633028,/content/data/frame1324.jpg,0
1386,948.107856,341.820992,316.554253,407.752556,0.996157,952.325526,956.326760,963.304073,973.169388,990.193857,...,0.208177,0.502651,0.000757,0.001361,0.003120,0.046070,0.000673,0.445368,/content/data/frame1325.jpg,0
1387,947.277669,340.831570,318.305013,409.080357,0.995794,951.226396,955.393790,962.488553,972.388618,989.453406,...,0.131733,0.509219,0.000674,0.002093,0.001647,0.085060,0.000581,0.400726,/content/data/frame1326.jpg,0
1388,947.097005,342.439453,319.181207,405.087547,0.995722,951.975884,955.991472,963.117106,973.159196,990.286696,...,0.184203,0.463511,0.000629,0.001471,0.002408,0.107825,0.000557,0.423599,/content/data/frame1327.jpg,0
1389,949.306641,345.048878,316.355252,399.636990,0.996680,952.400745,956.519309,963.526148,973.279885,990.274396,...,0.158188,0.413544,0.001480,0.002351,0.003887,0.119123,0.001218,0.458396,/content/data/frame1328.jpg,0

In [ ]:
l1 = []

In [ ]:
for i in range(0,len(data)):
  if data['AU06'][i]<0.5 and data['AU12'][i]<0.5 :
    l1.append("yes")
  else:
    l1.append("no")
data['Are there signs of Unusual/ excessive smiling?'] = l1
l1 = []
for i in range(0,len(data)):
  if data['AU43'][i]>0.2 and data['AU06'][i]<0.5 and 0.2<data['AU09'][i]<0.6:
    l1.append("yes")
  else:
    l1.append("no")
data['Is the face asymmetric(FA)?'] = l1
l1 = []
for i in range(0,len(data)):
  if(0.5>data['AU25'][i] and 0.5>data['AU26'][i]):
    l1.append("yes")
  else:
    l1.append("no")
data['Are their lips parted?'] = l1
l1 = []
for i in range(0,len(data)):
  if 0.5>data['AU06'][i]:
    l1.append("yes")
  else:
    l1.append("no")
data['Are cheeks puffed or raised with happiness?'] = l1
l1 = []
for i in range(0,len(data)):
  if data['AU20'][i] == 0:
    l1.append("yes")
  else:
    l1.append("no")
data['Are there any noticeable lip movements, (such as lip pursing, biting, or smacking, exhibited by the child in the video) ?'] = l1
l1 = []
for i in range(0,len(data)):
  if 0.4 > data['AU15'][i]:
    l1.append("yes")
  else:
    l1.append("no")
data['Does the lip corner depressor show discomfort or stress?'] = l1
l1 = []
for i in range(0,len(data)):
  if(0.5>data['AU25'][i] and 0.5>data['AU26'][i]):
    l1.append("yes")
  else:
    l1.append("no")
data['Are there signs of jaw clenching or teeth grinding?'] = l1
l1 = []
for i in range(0,len(data)):
  if(0.3<data['AU43'][i]):
    l1.append("yes")
  else:
    l1.append("no")
data[' Does the child have reduced eye contact?'] = l1
l1 = []
for i in range(0,len(data)):
  if(0.3<data['AU43'][i]):
    l1.append("yes")
  else:
    l1.append("no")
data['Does the child have atypical gaze patterns?'] = l1
l1 = []
for i in range(0,len(data)):
  if(0.4<data['AU04'][i]):
    l1.append("yes")
  else:
    l1.append("no")
data['Are the inner portions of the brows furrowed horizontally?'] = l1
l1 = []
for i in range(0,len(data)):
  if(0.45<data['AU01'][i]):
    l1.append("yes")
  else:
    l1.append("no")
data['Is there absence of the inner brow raiser?'] = l1

In [ ]:
data

,FaceRectX,FaceRectY,FaceRectWidth,FaceRectHeight,FaceScore,x_0,x_1,x_2,x_3,x_4,...,Is the face asymmetric(FA)?,Are their lips parted?,Are cheeks puffed or raised with happiness?,"Are there any noticeable lip movements, (such as lip pursing, biting, or smacking, exhibited by the child in the video) ?",Does the lip corner depressor show discomfort or stress?,Are there signs of jaw clenching or teeth grinding?,Does the child have reduced eye contact?,Does the child have atypical gaze patterns?,Are the inner portions of the brows furrowed horizontally?,Is there absence of the inner brow raiser?
0,865.570692,336.203133,317.611057,407.807968,0.998354,859.437006,864.554202,873.272245,885.788089,905.461516,...,no,yes,yes,yes,yes,yes,no,no,no,no
1,865.890245,333.035362,319.283474,412.016899,0.998237,856.599958,862.850322,872.695581,885.721312,905.220978,...,no,yes,yes,yes,yes,yes,no,no,no,no
2,865.740994,334.909630,317.141819,408.372253,0.997989,855.189773,861.477001,871.240480,884.175150,903.595056,...,no,yes,yes,yes,yes,yes,no,no,no,no
3,863.868815,334.156792,313.655382,410.975189,0.998086,855.206640,861.090611,870.471204,883.376778,902.641975,...,yes,yes,yes,yes,yes,yes,yes,yes,no,no
4,864.068142,331.252728,308.735243,410.773899,0.998166,851.017937,858.243559,868.302964,881.814315,901.802886,...,yes,yes,yes,yes,yes,yes,yes,yes,no,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1385,955.890734,329.181942,317.982964,408.483799,0.996393,948.038917,951.542771,958.343730,968.663875,985.946973,...,no,yes,yes,yes,yes,yes,no,no,yes,no
1386,948.107856,341.820992,316.554253,407.752556,0.996157,952.325526,956.326760,963.304073,973.169388,990.193857,...,yes,yes,yes,yes,yes,yes,no,no,no,no
1387,947.277669,340.831570,318.305013,409.080357,0.995794,951.226396,955.393790,962.488553,972.388618,989.453406,...,no,yes,yes,yes,yes,yes,no,no,no,no
1388,947.097005,342.439453,319.181207,405.087547,0.995722,951.975884,955.991472,963.117106,973.159196,990.286696,...,no,yes,yes,yes,yes,yes,no,no,no,no
1389,949.306641,345.048878,316.355252,399.636990,0.996680,952.400745,956.519309,963.526148,973.279885,990.274396,...,no,yes,yes,yes,yes,yes,no,no,yes,no

In [ ]:
data.to_csv('video_threshold.csv')